SELECT D.NAME AS DEPARTMENT, E1.NAME AS EMPLOYEE, E1.SALARY 
FROM EMPLOYEE E1 
JOIN DEPARTMENT D ON E1.DepartmentId = D.Id
WHERE E1.SALARY = (SELECT MAX(SALARY) FROM
                 EMPLOYEE E2 WHERE E2.DepartmentId = E1.DepartmentId)